### ISSUE TITLE
lint: add tslint setup

### ISSUE THREAD

**Issue by vcapretz** [pagarme/superbowleto#208]
## Description

Using linting tools is very important for code pattern and as you use TypeScript, changing from eslint to [tslint](https://palantir.github.io/tslint/usage/cli/) could bring more validations specific to TypeScript, it can extend eslint configs and also check for other stuff. What do you think about it?

**Comment by Thor99** [comment]
That's a nice idea! Would you mind open a PR?

**Comment by vcapretz** [comment]
No problem! I’ll do it! 

VS Code also integrates very well with the tslint plugin (just a tip for who uses it 😉)

**Comment by vcapretz** [comment]
After setting up tslint there were some new errors, should I treat them in this same issue (and in one PR), or in multiple ones?

![image](https://user-images.githubusercontent.com/14620121/28474595-a6371cbc-6e1f-11e7-8f81-53df9b657b0e.png)

**Comment by felquis** [comment]
@vcapretz in this situation I'd do the following:

1. we first add the linter commit it
1. then use the fix and commit the automatic fixes
1. then fix manually the remaining warnings, commit then

All in one PR because we don't want the CI failing in the master branch.
