### ISSUE TITLE
Why not findById?

### ISSUE THREAD

**Issue by icarotav** [pagarme/superbowleto#238]
Why not findById instead findOne, on src/resources/boleto/service.ts update method?

**Comment by vcapretz** [comment]
Actually they are exactly the same, as you can check the source: https://github.com/Automattic/mongoose/blob/8cb0e355f75140bd4506a80b21dd94244f828cb0/lib/model.js#L1067-L1069 

But I think that using `findOne` and passing the `id` field makes easier when you need to add other field to query the data
