### ISSUE TITLE
Boletos registrados, remesas

### ISSUE THREAD

**Issue by GlauberF** [pagarme/superbowleto#289]
## Help

Olá, curti bastante a iniciativa e estou buscando algo, porem tenho algumas dúvidas.

1 - existe uma documentação mais elaborada
2 - consigo gerar boleto registrado
3 - consigo gerar remesa
4 - como faço para incluir um novo banco , uma documentação para isso ? com isso também posso contribuir com o projeto.

**Comment by GlauberF** [comment]
Perfeito, irei testar

**Comment by GlauberF** [comment]
Perfeito,
Por exemplo para o banco que hoje esta rodando Bradesco, posso fazer uso/emissão de boletos registrados e não registrados, certo ?
Se sim, com isso eu vejo como foi implementado e me baseio para outros bancos.

E quando falo remessa é a questão de gerar os CNAB 400|240, obter retorno EDI,r baixa automática do boleto etc...

**Comment by otaviopace** [comment]
Para gerar um boleto não é necessário nenhum banco. Um boleto nada mais é do que um número o qual representa uma transferência de um valor de uma conta para outra. Porém para esse boleto gerado ser válido, é necessário ter uma carteira de boletos no banco. Para gerar o número desses boletos utilizamos a nossa biblioteca [node-boleto](https://github.com/pagarme/node-boleto). Já para o registro de boletos é necessário uma comunicação com um banco que registra. No caso o `superbowleto` possui a comunicação somente com o banco Bradesco.

Lembrando que quando se emite para um banco x, deve se registrar no mesmo. Além do que a partir de 21/07/2018 todos os boletos deveriam ser registrados, segundo o cronograma da FEBRABAN.

Quando se fala de processamento de `edi files` o  `superbowleto` não possui nada implementado para tal, sua responsabilidade envolve apenas o registro de boletos.

Portanto para conciliar os boletos emitidos/registrados é necessário se comunicar com uma empresa que fornece serviço de VAN (Value Added Network). Através dela conseguirá realizar a troca desses arquivos de forma segura :slightly_smiling_face:

**Comment by GlauberF** [comment]
Perfeito @otaviopace , agora estamos alinhados hehe, então acho que talvez eu me expressei mal.
Minha dúvida/pergunta/guide é, como eu faço para criar uma nova comunicação, com outro banco ?

E segundo, verifiquei que tem **auth**, qual rota utilizo para registrar um novo user, para utilizar o microserviço ?

# Sugestão
sou ADM da página mundo javascript, o que você acha de fazermos um hangout mais técnico/prático sobre o **superbowleto** , com isso alem de ter como registro um vídeo que explana melhor o ecossistema, também podemos encontrar novas pessoas para contribuir com o projeto. podendo levar a outro patamar.
sobre isso, podemos conversar via **linkedin**: https://www.linkedin.com/in/glauber-funez/

**Comment by otaviopace** [comment]
Para criar uma nova comunicação com um novo banco seria necessário adicionar uma nova pasta [aqui](https://github.com/pagarme/superbowleto/tree/master/src/providers) com o nome do novo banco o qual irá se integrar. Eu recomendo dar uma olhada na pasta do `bradesco` para ter uma noção de como uma integração pode ser feita :slightly_smiling_face: 

Quanto a autenticação o serviço, ela é feita por esse [middleware](https://github.com/pagarme/superbowleto/blob/master/src/middlewares/authentication.js). Ela funciona da seguinte forma: toda requisição enviada ao `superbowleto` precisa de um `header` HTTP chamado `x-api-key`, então ao passá-lo, será verificado se ele é o mesmo que existe em uma chave no `credstash` (serviço de chave e valor encriptados pela Amazon). Ou seja, fica mais ou menos assim:

![superbowleto_diagrama_autenticacao](https://user-images.githubusercontent.com/15306309/44098039-7f5e2fea-9fb5-11e8-9f81-fc97606b77f9.png)

Eu topo com certeza uma call para falarmos mais sobre o projeto! Como podemos realizá-la?

**Comment by GlauberF** [comment]
Pefeito @otaviopace , então mandei uma solicitação no linkedin para você, vamos alinhar por lá a call/live

**Comment by mariohmol** [comment]
Olá!! Me tira uma dúvida? Esta comunicação de boleto a registrar, é possível ser feito direto ao banco ou temos que usar algum serviço da pagar.me para enviar?

Outra coisa, existe alguma implementação para geração de CNAB (arquivo remessa) ?

Obrigado!

**Comment by mariohmol** [comment]
Obrigado pela resposta! 
Fiquei na duvida como funciona essa comunicacao direta com o banco, alguma referencia ou doc?

Iniciei um projeto de cnab se alguem interessar em colaborar

https://github.com/mariohmol/nodejs-cnab
