### ISSUE TITLE
Integração ShopFácil/Bradesco

### ISSUE THREAD

**Issue by jonatasoc** [pagarme/superbowleto#357]
Bom dia, pessoal!

Que projeto legal esse daqui!

Estou desenvolvendo um app para consulta e geração de boletos no banco Bradesco e quero usar esse serviço para integrar com ele. Sugiram algumas dúvidas:

1 - É necessário assinar os serviços AWS Fargate e AWS SQS para utilizar o serviço?
2 - As APIs key do Bradesco e ShopFácil devem ficar dentro do .env, correto? Essas APIs são obtidas diretamente com eles, correto?
3 - Existe também alguma tarefa no serviço para verificar se um boleto já foi pago?

Obrigado, pessoal!

**Comment by lucianopf** [comment]
Opa mestre, que massa que tu achou o projeto! 😬 

1 - Não é necessário rodar o projeto no ECS Fargate mas hoje caso o seu desejo seja registrar boletos de forma async com retentativas o ideal é ter um SQS mesmo pra lidar com os boletos no worker.

2 - Isso, essas são as chaves que tu vai conseguir criando uma conta lá com eles e dps preencher as variáveis de ambiente de alguma forma, ou usando o `.env` ou definindo os valores nas envs do container daí [aqui](https://github.com/pagarme/superbowleto/blob/master/src/config/providers.js#L23-L28) que carrega os valores 😬 

3 - Infelizmente não @jonatasoc , o projeto é mais focado em registrar boletos, a conciliação é feita por outras aplicações por troca de arquivos posicionais 😬

**Comment by jonatasoc** [comment]
Rapaz, me senti até importante agora recebendo uma resposta do mestre dos mestres. hahaha

Show, Luciano! Respondeu plenamente às minhas dúvidas.

Vou rodar o projeto aqui e começar a testar as rotas. 

Tá sendo um parto obter a API key com o Bradesco e ShopFácil 😑😑.

Value, Luciano!
